### PR TITLE
[fixup]: Don't rescan during upgrade

### PR DESCRIPTION
**Pull request by iilyak**
This is the same fix as in here https://github.com/cloudant/couch_replicator/commit/7eb811aa11d21129f620e7bfbd2c559771c7be00.  

Rescanning during upgrade causes all replication jobs to move to new
nodes and then back again. This was avoided in the normal 'hot'
upgrade case as no nodeup/nodedown events occurred.

Note: This is a fixup commit. **We would need to strip it out of the history
when we would be merging to upstream.**

This PR depends on https://github.com/cloudant/showroom/pull/76

BugzID: 52826
BugzID: 69914

### CODE REVIEW

**Comment by eiri** [comment]
lgtm

**Comment by nickva** [comment]
+1 looks good. 

For upstream we might not need this soon. In the new replicator work this is handled as hold-off. After there is a nodeup/nodedown, don't rescan right way, rather wait a bit for more for cluster changes. Then if there are no more changes in a given period of time, initiate a rescan.

**Comment by rnewson** [comment]
with this code, what will trigger the rescan after the upgrade? My guess is nothing, which means the operator will need to remember to trigger it manually when they're done.

**Comment by nickva** [comment]
@rnewson rawhide tool has code to trigger rescan after all nodes upgraded

**Pull request merged**
